FROM python:3.10

# Устанавливаем необходимые библиотеки
RUN pip install --upgrade pip
RUN pip install allure-pytest pytest

# Копируем требования
COPY requirements.txt .

# Устанавливаем зависимости из requirements.txt
RUN pip install -r requirements.txt

# Рабочая директория
WORKDIR /app

# Указываем, что контейнер будет запускать по умолчанию
CMD ["pytest"]
